# Generated by Django 4.1.2 on 2022-11-29 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('second_name', models.CharField(max_length=150, verbose_name='Second name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('gender', models.CharField(max_length=30, verbose_name='Gender')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.photoclient', verbose_name='Photo')),
            ],
        ),
    ]
