# Generated by Django 4.1.2 on 2022-11-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoclient',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.clientprofile'),
        ),
        migrations.AlterField(
            model_name='photoclient',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='Photo'),
        ),
    ]
