# Generated by Django 4.1.2 on 2022-11-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_photoclient_client_id_alter_photoclient_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoclient',
            name='client_id',
        ),
    ]
