# Generated by Django 4.1.2 on 2022-11-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_photoclient_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='photo',
            new_name='photo_id',
        ),
    ]
