# Generated by Django 4.1.2 on 2022-11-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_photo_clientprofile_photo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='photoclient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Photo'),
        ),
    ]
