# Generated by Django 4.1.2 on 2022-11-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_photo_id_clientprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoclient',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.clientprofile', verbose_name='Client'),
            preserve_default=False,
        ),
    ]
