# Generated by Django 4.1.2 on 2022-11-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_photoclient_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='photo',
        ),
    ]
