# Generated by Django 4.1.2 on 2022-11-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_clientprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='photo',
        ),
    ]
