# Generated by Django 4.1.2 on 2022-11-30 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_clientprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoclient',
            name='client',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.photoclient', verbose_name='Photo'),
        ),
    ]
