# Generated by Django 4.1.2 on 2022-12-01 21:38

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_photoclient_client_clientprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoclient',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[300, 300], upload_to='images', verbose_name='Photo'),
        ),
    ]
