version: '3'

services:
  db:
    image: postgres:13
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vxdf44qwer
      POSTGRES_DB: redapp

  backend:
    build: ./
    privileged: true
    ports:
      - 8080:8080
    command: bash -c "
        python manage.py migrate &&
        export DJANGO_SUPERUSER_PASSWORD='zzzxxc23!' &&
        python manage.py createsuperuser --username niko99 --email ex@ex.com --noinput &&
        python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db